# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: StrategyCo.Global
email: rahul.abhisek@gmail.com
og-image: images/hero5.jpeg
description: > # this means to ignore newlines until "baseurl:"
  We offer business development and strategy consultancy. We use analytical and collaborative approach for strategy and implementation plan to achieve concrete results. We believe in achieving results and going one step further by following up on the plan with a clear timeline.
footer: All content Â© StrategyCo.Global 2017
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://strategycoglobal.com/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
include: ['_sections','_testimonials','_advisors','_team']
